export const restaurants = [
  {
    id: "r1",
    name: "Claro",
    chef: "Ran Shmueli",
    rating: 4,
    image: "/images/restaurants/claro.jpg",
  },
  {
    id: "r2",
    name: "Kab Kem",
    chef: "Yariv Malili",
    rating: 3,
    image: "/images/restaurants/kab-kem.jpg",
  },
  {
    id: "r3",
    name: "Messa",
    chef: "Aviv Moshe",
    rating: 1,
    image: "/images/restaurants/messa-2.jpg",
  },
  {
    id: "r4",
    name: "Nitan Thai",
    chef: "Shahaf Shabtay",
    rating: 4,
    image: "/images/restaurants/nithan-thai.jpg",
  },
  {
    id: "r5",
    name: "Tiger Lily",
    chef: "Yanir Green",
    rating: 4,
    image: "/images/restaurants/tiger-lily.jpg",
  },
  {
    id: "r6",
    name: "Ya pan",
    chef: "Yuval Ben Moshe",
    rating: 3,
    image: "/images/restaurants/yapan.jpg",
  },
  {
    id: "r7",
    name: "Thai Thai",
    chef: "Yossi Shitrit",
    rating: 4,
    image: "/images/restaurants/claro-2.jpg",
  },
  {
    id: "r8",
    name: "Kab Kem Diner",
    chef: "Yariv Malili",
    rating: 2,
    image: "/images/restaurants/kab-kem-diner.png",
  },
  {
    id: "r9",
    name: "Lumina",
    chef: "Aviv Moshe",
    rating: 1,
    image: "/images/restaurants/Lumina.png",
  },
  {
    id: "r10",
    name: "Onza",
    chef: "Yossi Shitrit",
    rating: 4,
    image: "/images/restaurants/nithan-thai.jpg",
  },
  {
    id: "r11",
    name: "Kitchen Market",
    chef: "Yossi Shitrit",
    rating: 5,
    image: "/images/restaurants/Kitchen-Market.png",
  },
  {
    id: "r12",
    name: "Mashya",
    chef: "Yossi Shitrit",
    rating: 4,
    image: "/images/restaurants/Masya.png",
  },
];

export const dishes = [
  {
    id: "d1",
    restaurantId: "r1",
    mealType: "breakfast",
    name: "Claro Morning Bowl",
    image: "/images/dishes/pad-ki-mao.jpg",
    description: "Warm grains, roasted vegetables, soft herbs and tahini.",
    price: 64,
    tags: ["vegetarian"],
  },
  {
    id: "d7",
    restaurantId: "r2",
    mealType: "breakfast",
    name: "Kab Kem Morning Noodles",
    image: "/images/dishes/Lumina.png",
    description: "Light wok-fried noodles with herbs and vegetables.",
    price: 58,
    tags: ["vegan"],
  },
  {
    id: "d13",
    restaurantId: "r3",
    mealType: "breakfast",
    name: "Messa Granola Bowl",
    image: "/images/dishes/pad-ki-mao-2.png",
    description: "House granola, seasonal fruit and coconut cream.",
    price: 52,
    tags: ["vegan"],
  },
  {
    id: "d19",
    restaurantId: "r4",
    mealType: "breakfast",
    name: "Nitan Thai Rice Bowl",
    image: "/images/dishes/pad-ki-mao.jpg",
    description: "Steamed rice, pickled vegetables and soft herbs.",
    price: 49,
    tags: ["vegan"],
  },
  {
    id: "d25",
    restaurantId: "r5",
    mealType: "breakfast",
    name: "Tiger Lily Morning Farm",
    image: "/images/dishes/Lumina.png",
    description: "Warm grain salad, vegetables and tahini.",
    price: 54,
    tags: ["vegan"],
  },
  {
    id: "d31",
    restaurantId: "r6",
    mealType: "breakfast",
    name: "Ya Pan Morning Bowl",
    image: "/images/dishes/pad-ki-mao-2.png",
    description: "Rice, pickles and soft herbs.",
    price: 48,
    tags: ["vegan"],
  },
  {
    id: "d37",
    restaurantId: "r7",
    mealType: "breakfast",
    name: "Thai Thai Morning Bowl",
    image: "/images/dishes/pad-ki-mao.jpg",
    description: "Grains, greens and soft herbs.",
    price: 55,
    tags: ["vegan"],
  },
  {
    id: "d43",
    restaurantId: "r8",
    mealType: "breakfast",
    name: "Kab Kem 2 Morning Noodles",
    image: "/images/dishes/Lumina.png",
    description: "Light noodles with herbs and vegetables.",
    price: 56,
    tags: ["vegan"],
  },
  {
    id: "d49",
    restaurantId: "r9",
    mealType: "breakfast",
    name: "Messa 2 Granola Bowl",
    image: "/images/dishes/pad-ki-mao-2.png",
    description: "Granola, fruit and coconut yogurt.",
    price: 53,
    tags: ["vegan"],
  },
  {
    id: "d55",
    restaurantId: "r10",
    mealType: "breakfast",
    name: "Onza Morning Farm",
    image: "/images/dishes/pad-ki-mao.jpg",
    description: "Warm grains, herbs and tahini.",
    price: 52,
    tags: ["vegan"],
  },
  {
    id: "d61",
    restaurantId: "r11",
    mealType: "breakfast",
    name: "Kitchen Market Granola",
    image: "/images/dishes/Lumina.png",
    description: "Granola, fruit and yogurt.",
    price: 51,
    tags: ["vegetarian"],
  },
  {
    id: "d67",
    restaurantId: "r12",
    mealType: "breakfast",
    name: "Mashya Morning Farm",
    image: "/images/dishes/pad-ki-mao-2.png",
    description: "Warm grains, vegetables and tahini.",
    price: 55,
    tags: ["vegan"],
  },
  {
    id: "d2",
    restaurantId: "r1",
    mealType: "breakfast",
    name: "Claro Green Shakshuka",
    image: "/images/dishes/red-farm.jpg",
    description: "Eggs in green herb sauce, labneh and grilled bread.",
    price: 72,
    tags: ["vegetarian"],
  },
  {
    id: "d8",
    restaurantId: "r2",
    mealType: "breakfast",
    name: "Kab Kem Rice Porridge",
    image: "/images/dishes/Masya.png",
    description:
      "Savory rice porridge, scallions, chili oil and crispy garlic.",
    price: 62,
    tags: ["vegetarian"],
  },
  {
    id: "d14",
    restaurantId: "r3",
    mealType: "breakfast",
    name: "Messa Morning Pad",
    image: "/images/dishes/red-farm-2.png",
    description: "Light noodles with herbs, lime and crispy shallots.",
    price: 61,
    tags: ["vegetarian"],
  },
  {
    id: "d20",
    restaurantId: "r4",
    mealType: "breakfast",
    name: "Nitan Thai Herb Omelette",
    image: "/images/dishes/red-farm.jpg",
    description: "Fluffy omelette with fresh herbs and chili oil.",
    price: 59,
    tags: ["vegetarian"],
  },
  {
    id: "d26",
    restaurantId: "r5",
    mealType: "breakfast",
    name: "Tiger Lily Sesame Noodles",
    image: "/images/dishes/Masya.png",
    description: "Cold noodles, sesame dressing and herbs.",
    price: 63,
    tags: ["vegetarian"],
  },
  {
    id: "d32",
    restaurantId: "r6",
    mealType: "breakfast",
    name: "Ya Pan Herb Noodles",
    image: "/images/dishes/red-farm-2.png",
    description: "Herby noodles with sesame and citrus.",
    price: 57,
    tags: ["vegetarian"],
  },
  {
    id: "d38",
    restaurantId: "r7",
    mealType: "breakfast",
    name: "Thai Thai Herb Omelette",
    image: "/images/dishes/red-farm.jpg",
    description: "Herb omelette with chili and labneh.",
    price: 63,
    tags: ["vegetarian"],
  },
  {
    id: "d44",
    restaurantId: "r8",
    mealType: "breakfast",
    name: "Kab Kem 2 Rice Porridge",
    image: "/images/dishes/Masya.png",
    description: "Savory porridge with chili oil and scallions.",
    price: 60,
    tags: ["vegetarian"],
  },
  {
    id: "d50",
    restaurantId: "r9",
    mealType: "breakfast",
    name: "Messa 2 Morning Pad",
    image: "/images/dishes/red-farm-2.png",
    description: "Herby noodles with sesame and crispy shallots.",
    price: 62,
    tags: ["vegetarian"],
  },
  {
    id: "d56",
    restaurantId: "r10",
    mealType: "breakfast",
    name: "Onza Herb Omelette",
    image: "/images/dishes/red-farm.jpg",
    description: "Fluffy omelette with herbs and chili.",
    price: 60,
    tags: ["vegetarian"],
  },
  {
    id: "d62",
    restaurantId: "r11",
    mealType: "breakfast",
    name: "Kitchen Market Morning Pad",
    image: "/images/dishes/Masya.png",
    description: "Noodles with fresh herbs and sesame.",
    price: 60,
    tags: ["vegetarian"],
  },
  {
    id: "d68",
    restaurantId: "r12",
    mealType: "breakfast",
    name: "Mashya Herb Omelette",
    image: "/images/dishes/red-farm-2.png",
    description: "Herb omelette with spicy tomato salad.",
    price: 63,
    tags: ["vegetarian"],
  },
  {
    id: "d3",
    restaurantId: "r1",
    mealType: "lunch",
    name: "Claro Lunch Pad Ki Mao",
    image: "/images/dishes/ta-ma-la-ko.jpg",
    description:
      "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce.",
    price: 88,
    tags: ["vegan", "spicy"],
  },
  {
    id: "d9",
    restaurantId: "r2",
    mealType: "lunch",
    name: "Kab Kem Pad Ki Mao",
    image: "/images/dishes/Kitchen-Market.png",
    description:
      "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce.",
    price: 86,
    tags: ["spicy"],
  },
  {
    id: "d15",
    restaurantId: "r3",
    mealType: "lunch",
    name: "Messa Pad Ki Mao",
    image: "/images/dishes/Frito.png",
    description:
      "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce.",
    price: 92,
    tags: ["vegan", "spicy"],
  },
  {
    id: "d21",
    restaurantId: "r4",
    mealType: "lunch",
    name: "Nitan Thai Pad Ki Mao",
    image: "/images/dishes/ta-ma-la-ko.jpg",
    description:
      "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce.",
    price: 90,
    tags: ["spicy"],
  },
  {
    id: "d27",
    restaurantId: "r5",
    mealType: "lunch",
    name: "Tiger Lily Pad Ki Mao",
    image: "/images/dishes/Kitchen-Market.png",
    description:
      "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce.",
    price: 89,
    tags: ["spicy"],
  },
  {
    id: "d33",
    restaurantId: "r6",
    mealType: "lunch",
    name: "Ya Pan Pad Ki Mao",
    image: "/images/dishes/Frito.png",
    description:
      "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce.",
    price: 87,
    tags: ["spicy"],
  },
  {
    id: "d39",
    restaurantId: "r7",
    mealType: "lunch",
    name: "Thai Thai Pad Ki Mao",
    image: "/images/dishes/ta-ma-la-ko.jpg",
    description:
      "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce.",
    price: 90,
    tags: ["spicy"],
  },
  {
    id: "d45",
    restaurantId: "r8",
    mealType: "lunch",
    name: "Kab Kem 2 Pad Ki Mao",
    image: "/images/dishes/Kitchen-Market.png",
    description:
      "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce.",
    price: 88,
    tags: ["spicy"],
  },
  {
    id: "d51",
    restaurantId: "r9",
    mealType: "lunch",
    name: "Messa 2 Pad Ki Mao",
    image: "/images/dishes/Frito.png",
    description:
      "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce.",
    price: 91,
    tags: ["spicy"],
  },
  {
    id: "d57",
    restaurantId: "r10",
    mealType: "lunch",
    name: "Onza Street Pad Ki Mao",
    image: "/images/dishes/ta-ma-la-ko.jpg",
    description: "Wok-fried noodles, herbs and chili.",
    price: 85,
    tags: ["spicy"],
  },
  {
    id: "d63",
    restaurantId: "r11",
    mealType: "lunch",
    name: "Kitchen Market Red Farm",
    image: "/images/dishes/Kitchen-Market.png",
    description: "Tofu, vegetables and spicy sauce.",
    price: 88,
    tags: ["vegan"],
  },
  {
    id: "d69",
    restaurantId: "r12",
    mealType: "lunch",
    name: "Mashya Signature Red Farm",
    image: "/images/dishes/Frito.png",
    description: "House version of Red Farm with grilled pear and herbs.",
    price: 102,
    tags: ["vegan"],
  },
  {
    id: "d4",
    restaurantId: "r1",
    mealType: "lunch",
    name: "Claro Red Farm",
    image: "/images/dishes/pad-ki-mao-2.png",
    description: "Tofu, Spekkoek Peanuts, Spicy Manis, Pear Yakitori.",
    price: 94,
    tags: ["vegetarian", "vegan"],
  },
  {
    id: "d10",
    restaurantId: "r2",
    mealType: "lunch",
    name: "Kab Kem Red Farm",
    image: "/images/dishes/pad-ki-mao.jpg",
    description: "Tofu, Spicy Manis, roasted peanuts, crunchy vegetables.",
    price: 89,
    tags: ["vegan"],
  },
  {
    id: "d16",
    restaurantId: "r3",
    mealType: "lunch",
    name: "Messa Red Farm",
    image: "/images/dishes/Lumina.png",
    description: "Tofu, Spekkoek Peanuts, Spicy Manis, Pear Yakitori.",
    price: 97,
    tags: ["vegetarian", "vegan"],
  },
  {
    id: "d22",
    restaurantId: "r4",
    mealType: "lunch",
    name: "Nitan Thai Red Farm",
    image: "/images/dishes/pad-ki-mao-2.png",
    description: "Tofu, peanuts, spicy sauce, crunchy vegetables.",
    price: 95,
    tags: ["vegan"],
  },
  {
    id: "d28",
    restaurantId: "r5",
    mealType: "lunch",
    name: "Tiger Lily Red Farm",
    image: "/images/dishes/pad-ki-mao.jpg",
    description: "Tofu, Spicy Manis, Pear Yakitori and herbs.",
    price: 93,
    tags: ["vegetarian", "vegan"],
  },
  {
    id: "d34",
    restaurantId: "r6",
    mealType: "lunch",
    name: "Ya Pan Red Farm",
    image: "/images/dishes/Lumina.png",
    description: "Tofu, peanuts and spicy sauce.",
    price: 90,
    tags: ["vegan"],
  },
  {
    id: "d40",
    restaurantId: "r7",
    mealType: "lunch",
    name: "Thai Thai Red Farm",
    image: "/images/dishes/pad-ki-mao-2.png",
    description: "Tofu, spicy sauce, roasted vegetables.",
    price: 94,
    tags: ["vegan"],
  },
  {
    id: "d46",
    restaurantId: "r8",
    mealType: "lunch",
    name: "Kab Kem 2 Red Farm",
    image: "/images/dishes/pad-ki-mao.jpg",
    description: "Tofu, Spicy Manis, roasted peanuts, herbs.",
    price: 92,
    tags: ["vegan"],
  },
  {
    id: "d52",
    restaurantId: "r9",
    mealType: "lunch",
    name: "Messa 2 Red Farm",
    image: "/images/dishes/Lumina.png",
    description: "Tofu, Spicy Manis, Pear Yakitori.",
    price: 96,
    tags: ["vegetarian", "vegan"],
  },
  {
    id: "d58",
    restaurantId: "r10",
    mealType: "lunch",
    name: "Onza Red Farm",
    image: "/images/dishes/pad-ki-mao-2.png",
    description: "Tofu, Spicy Manis, roasted vegetables.",
    price: 90,
    tags: ["vegan"],
  },
  {
    id: "d64",
    restaurantId: "r11",
    mealType: "lunch",
    name: "Kitchen Market Pad Ki Mao",
    image: "/images/dishes/pad-ki-mao.jpg",
    description:
      "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce.",
    price: 90,
    tags: ["spicy"],
  },
  {
    id: "d70",
    restaurantId: "r12",
    mealType: "lunch",
    name: "Mashya Pad Ki Mao",
    image: "/images/dishes/Lumina.png",
    description:
      "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce.",
    price: 92,
    tags: ["spicy"],
  },
  {
    id: "d5",
    restaurantId: "r1",
    mealType: "dinner",
    name: "Claro Ta Ma La Ko",
    image: "/images/dishes/red-farm-2.png",
    description:
      "Shrimps, Glass Noodles, Kemiri Nuts, Shallots, Lemon Grass, Magic Chili Brown Coconut.",
    price: 98,
    tags: ["spicy"],
  },
  {
    id: "d11",
    restaurantId: "r2",
    mealType: "dinner",
    name: "Kab Kem Ta Ma La Ko",
    image: "/images/dishes/red-farm.jpg",
    description:
      "Shrimps, Glass Noodles, Kemiri Nuts, Shallots, Lemon Grass, Magic Chili Brown Coconut.",
    price: 104,
    tags: ["spicy"],
  },
  {
    id: "d17",
    restaurantId: "r3",
    mealType: "dinner",
    name: "Messa Ta Ma La Ko",
    image: "/images/dishes/Masya.png",
    description:
      "Shrimps, Glass Noodles, Kemiri Nuts, Shallots, Lemon Grass, Magic Chili Brown Coconut.",
    price: 108,
    tags: ["spicy"],
  },
  {
    id: "d23",
    restaurantId: "r4",
    mealType: "dinner",
    name: "Nitan Thai Ta Ma La Ko",
    image: "/images/dishes/red-farm-2.png",
    description:
      "Shrimps, Glass Noodles, Kemiri Nuts, Shallots, Lemon Grass, Magic Chili Brown Coconut.",
    price: 112,
    tags: ["spicy"],
  },
  {
    id: "d29",
    restaurantId: "r5",
    mealType: "dinner",
    name: "Tiger Lily Ta Ma La Ko",
    image: "/images/dishes/red-farm.jpg",
    description:
      "Shrimps, Glass Noodles, Kemiri Nuts, Shallots, Lemon Grass, Magic Chili Brown Coconut.",
    price: 110,
    tags: ["spicy"],
  },
  {
    id: "d35",
    restaurantId: "r6",
    mealType: "dinner",
    name: "Ya Pan Ta Ma La Ko",
    image: "/images/dishes/Masya.png",
    description:
      "Shrimps, Glass Noodles, Kemiri Nuts, Shallots, Lemon Grass, Magic Chili Brown Coconut.",
    price: 109,
    tags: ["spicy"],
  },
  {
    id: "d41",
    restaurantId: "r7",
    mealType: "dinner",
    name: "Thai Thai Ta Ma La Ko",
    image: "/images/dishes/red-farm-2.png",
    description:
      "Shrimps, Glass Noodles, Kemiri Nuts, Shallots, Lemon Grass, Magic Chili Brown Coconut.",
    price: 111,
    tags: ["spicy"],
  },
  {
    id: "d47",
    restaurantId: "r8",
    mealType: "dinner",
    name: "Kab Kem 2 Ta Ma La Ko",
    image: "/images/dishes/red-farm.jpg",
    description:
      "Shrimps, Glass Noodles, Kemiri Nuts, Shallots, Lemon Grass, Magic Chili Brown Coconut.",
    price: 110,
    tags: ["spicy"],
  },
  {
    id: "d53",
    restaurantId: "r9",
    mealType: "dinner",
    name: "Messa 2 Ta Ma La Ko",
    image: "/images/dishes/Masya.png",
    description:
      "Shrimps, Glass Noodles, Kemiri Nuts, Shallots, Lemon Grass, Magic Chili Brown Coconut.",
    price: 109,
    tags: ["spicy"],
  },
  {
    id: "d59",
    restaurantId: "r10",
    mealType: "dinner",
    name: "Onza Ta Ma La Ko",
    image: "/images/dishes/red-farm-2.png",
    description:
      "Shrimps, Glass Noodles, Kemiri Nuts, Shallots, Lemon Grass, Magic Chili Brown Coconut.",
    price: 108,
    tags: ["spicy"],
  },
  {
    id: "d65",
    restaurantId: "r11",
    mealType: "dinner",
    name: "Kitchen Market Ta Ma La Ko",
    image: "/images/dishes/red-farm.jpg",
    description:
      "Shrimps, Glass Noodles, Kemiri Nuts, Shallots, Lemon Grass, Magic Chili Brown Coconut.",
    price: 107,
    tags: ["spicy"],
  },
  {
    id: "d71",
    restaurantId: "r12",
    mealType: "dinner",
    name: "Mashya Ta Ma La Ko Deluxe",
    image: "/images/dishes/Masya.png",
    description:
      "Shrimps, Glass Noodles, Kemiri Nuts, Shallots, Lemon Grass, Magic Chili Brown Coconut, fresh herbs.",
    price: 112,
    tags: ["spicy"],
  },
  {
    id: "d6",
    restaurantId: "r1",
    mealType: "dinner",
    name: "Claro Night Farm",
    image: "/images/dishes/Frito.png",
    description: "Tofu, roasted peanuts, spicy coconut sauce and herbs.",
    price: 102,
    tags: ["vegan"],
  },
  {
    id: "d12",
    restaurantId: "r2",
    mealType: "dinner",
    name: "Kab Kem Chili Farm",
    image: "/images/dishes/ta-ma-la-ko.jpg",
    description: "Charred vegetables, chili, peanuts and sticky rice.",
    price: 99,
    tags: ["vegan", "spicy"],
  },
  {
    id: "d18",
    restaurantId: "r3",
    mealType: "dinner",
    name: "Messa Chili Farm",
    image: "/images/dishes/Kitchen-Market.png",
    description: "Tofu, grilled vegetables, chili, coriander and lime.",
    price: 103,
    tags: ["vegan", "spicy"],
  },
  {
    id: "d24",
    restaurantId: "r4",
    mealType: "dinner",
    name: "Nitan Thai Late Farm",
    image: "/images/dishes/Frito.png",
    description: "Charred vegetables, coconut, herbs and chili.",
    price: 106,
    tags: ["vegan", "spicy"],
  },
  {
    id: "d30",
    restaurantId: "r5",
    mealType: "dinner",
    name: "Tiger Lily Chili Farm",
    image: "/images/dishes/ta-ma-la-ko.jpg",
    description: "Tofu, vegetables, chili and coconut cream.",
    price: 104,
    tags: ["vegan", "spicy"],
  },
  {
    id: "d36",
    restaurantId: "r6",
    mealType: "dinner",
    name: "Ya Pan Late Farm",
    image: "/images/dishes/Kitchen-Market.png",
    description: "Roasted vegetables, coconut and chili.",
    price: 101,
    tags: ["vegan", "spicy"],
  },
  {
    id: "d42",
    restaurantId: "r7",
    mealType: "dinner",
    name: "Thai Thai Chili Farm",
    image: "/images/dishes/Frito.png",
    description: "Charred vegetables, peanuts and chili.",
    price: 105,
    tags: ["vegan", "spicy"],
  },
  {
    id: "d48",
    restaurantId: "r8",
    mealType: "dinner",
    name: "Kab Kem 2 Chili Farm",
    image: "/images/dishes/ta-ma-la-ko.jpg",
    description: "Charred vegetables, coconut and chili.",
    price: 104,
    tags: ["vegan", "spicy"],
  },
  {
    id: "d54",
    restaurantId: "r9",
    mealType: "dinner",
    name: "Messa 2 Chili Farm",
    image: "/images/dishes/Kitchen-Market.png",
    description: "Charred vegetables, peanuts and chili.",
    price: 103,
    tags: ["vegan", "spicy"],
  },
  {
    id: "d60",
    restaurantId: "r10",
    mealType: "dinner",
    name: "Onza Chili Farm",
    image: "/images/dishes/Frito.png",
    description: "Roasted vegetables, coconut and chili.",
    price: 102,
    tags: ["vegan", "spicy"],
  },
  {
    id: "d66",
    restaurantId: "r11",
    mealType: "dinner",
    name: "Kitchen Market Chili Farm",
    image: "/images/dishes/ta-ma-la-ko.jpg",
    description: "Charred vegetables, peanuts and chili.",
    price: 101,
    tags: ["vegan", "spicy"],
  },
  {
    id: "d72",
    restaurantId: "r12",
    mealType: "dinner",
    name: "Mashya Chili Farm",
    image: "/images/dishes/Kitchen-Market.png",
    description: "Roasted vegetables, coconut and chili.",
    price: 106,
    tags: ["vegan", "spicy"],
  },
];


export const chefs = [
  {
    id: "c1",
    name: "Asaf Granit",
    image: "/images/chefs/asaf-granit.png",
    description: "Mediterranean cuisine pioneer",
  },
  {
    id: "c2",
    name: "Aviv Moshe",
    image: "/images/chefs/aviv-moshe.png",
    description: "Chef of OCD, fine dining expert",
  },
  {
    id: "c3",
    name: "Yuval Ben Neriah",
    image: "/images/chefs/yuval-ben-neriah.png",
    description: "Asian fusion master",
  },
  {
    id: "c4",
    name: "Yossi Shitrit",
    image: "/images/chefs/yossi-shitrit.png",
    description:
      "Chef Yossi Shitrit has been living and breathing his culinary dreams for more than two decades, including running the kitchen in his first restaurant, the fondly-remembered Violet, located in Moshav  Udim. Shitrit's creativity and culinary  acumen born of long experience  are expressed in the every detail of each and every dish.",
  },
  {
    id: "c5",
    name: "Eyal Shani",
    image: "/images/chefs/eyal-shani.jpg",
    description: "Classic techniques, modern flavors",
  },
  {
    id: "c6",
    name: "Meir Adoni",
    image: "/images/chefs/meir-adoni.png",
    description: "Bold flavors and creative plates",
  },
  {
    id: "c7",
    name: "Omer Miller",
    image: "/images/chefs/omer-miller.png",
    description: "Seafood specialist",
  },
  {
    id: "c8",
    name: "Shahaf Shabtay",
    image: "/images/chefs/shahaf-shabtay.png",
    description: "French & Middle Eastern fusion",
  },
  {
    id: "c9",
    name: "Nitzan Raz",
    image: "/images/chefs/nitzan-raz.jpg",
    description: "Live-fire cooking expert",
  },
];
